--
--
CREATE TABLE stg.Turma(
	Id int NOT NULL,
	RegionalId smallint NULL,
	CodigoDaTurma nvarchar(20) NOT NULL,
	NomeUnidadeOperativa nvarchar(255) NOT NULL,
	NomeTurma nvarchar(255) NOT NULL,
	Sigla nvarchar(14) NOT NULL,
	AnoExercicio int NOT NULL,
	DivulgacaoOnline bit NOT NULL,
	DivulgacaoComMatriculaOnline bit NOT NULL,
	DataDeEncerramentoPresencial datetime2(7) NOT NULL,
	DataDeEncerramentoOnline datetime2(7) NULL,
	TotalVagas int NOT NULL,
	DataPeriodoExecucaoInicial datetime2(7) NOT NULL,
	DataPeriodoExecucaoFinal datetime2(7) NOT NULL,
	PlanoDoCursoId bigint NOT NULL,
	TurmaPlanejada bit NOT NULL,
	UnidadeOperativaId int NOT NULL,
	Situacao bit NOT NULL,
	Estado int NOT NULL,
	QuadroDeAcaoId int NOT NULL,
	CidadeId int NOT NULL,
	TurmaPlanejadaId int NULL,
	CargaHoraria int NOT NULL,
	RegimentoDeAvaliacaoId int NULL,
	DistribuirDiasLetivosParaUnidadeCurricularDoTipoPratica bit NOT NULL,
	DistribuirDiasLetivosParaUnidadeCurricularDoTipoPraticaAprendizagem bit NOT NULL,
	CodigoFormatado nvarchar(20) NOT NULL,
	DataTerminoInformativoContrato datetime2(7) NULL,
	DataCriacaoDaTurma datetime2(7) NOT NULL,
	IdLegado nvarchar(75) NULL,
	IgnorarValidacaoDiario bit NOT NULL,
	CargaHorariaCompleta int NOT NULL,
	DataAtualizacao datetime2(7) NOT NULL,
	IntegrarOffice365 bit NOT NULL,
	ComplementoDoNomeDaTurma nvarchar(75) NULL,
	InCompany bit NOT NULL,
	PlanoDoCursoDrDesatualizado bit NOT NULL,
	EscolaAberta bit NOT NULL,
	PeriodoDeExecucacaoFoiInformadoManualmente bit NOT NULL,
	LogAcao nvarchar(10) NOT NULL
) 
--
;

--
--
CREATE TABLE tgt.Turma(
	Id int NOT NULL,
	RegionalId smallint NULL,
	CodigoDaTurma nvarchar(20) NOT NULL,
	NomeUnidadeOperativa nvarchar(255) NOT NULL,
	NomeTurma nvarchar(255) NOT NULL,
	Sigla nvarchar(14) NOT NULL,
	AnoExercicio int NOT NULL,
	DivulgacaoOnline bit NOT NULL,
	DivulgacaoComMatriculaOnline bit NOT NULL,
	DataDeEncerramentoPresencial datetime2(7) NOT NULL,
	DataDeEncerramentoOnline datetime2(7) NULL,
	TotalVagas int NOT NULL,
	DataPeriodoExecucaoInicial datetime2(7) NOT NULL,
	DataPeriodoExecucaoFinal datetime2(7) NOT NULL,
	PlanoDoCursoId bigint NOT NULL,
	TurmaPlanejada bit NOT NULL,
	UnidadeOperativaId int NOT NULL,
	Situacao bit NOT NULL,
	Estado int NOT NULL,
	QuadroDeAcaoId int NOT NULL,
	CidadeId int NOT NULL,
	TurmaPlanejadaId int NULL,
	CargaHoraria int NOT NULL,
	RegimentoDeAvaliacaoId int NULL,
	DistribuirDiasLetivosParaUnidadeCurricularDoTipoPratica bit NOT NULL,
	DistribuirDiasLetivosParaUnidadeCurricularDoTipoPraticaAprendizagem bit NOT NULL,
	CodigoFormatado nvarchar(20) NOT NULL,
	DataTerminoInformativoContrato datetime2(7) NULL,
	DataCriacaoDaTurma datetime2(7) NOT NULL,
	IdLegado nvarchar(75) NULL,
	IgnorarValidacaoDiario bit NOT NULL,
	CargaHorariaCompleta int NOT NULL,
	DataAtualizacao datetime2(7) NOT NULL,
	IntegrarOffice365 bit NOT NULL,
	ComplementoDoNomeDaTurma nvarchar(75) NULL,
	InCompany bit NOT NULL,
	PlanoDoCursoDrDesatualizado bit NOT NULL,
	EscolaAberta bit NOT NULL,
	PeriodoDeExecucacaoFoiInformadoManualmente bit NOT NULL,
    ctrlArquivo varchar(255) null,
	ctrlDateIniIncr datetime null,
	ctrlDateFimIncr datetime null,
	ctrlAtivo smallint,
	ctrlInsert datetime null,
	ctrlUpdate datetime null,
	ctrlDelete datetime null 
) 
--
;